title: EFFICIENT FPGA IMPLEMENTATION FOR VISUAL OBJECT SEGMENTATION
description: Sowmya Reddy, Harshit Sharma, Keerthi Priya Lankapalli
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
